collections:
  terms:
    permalink: /:categories/:title:output_ext	
    output: true

  posts:
    permalink: /:categories/:title:output_ext	

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_terms"
      type: "terms"
    values:
      layout: "post"
      type: "term"
  -
    scope:
      path: ""
    values:
      layout: "default"			