collections:
  notes:
    permalink: /:categories/:title:output_ext	
    output: true

  posts:
    permalink: /:categories/:title:output_ext	
defaults:
  - scope:
      path: "/notes"
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
